apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-bus-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  clusterIP: None
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    rabbitmq: rabbitmq

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  selector:
    matchLabels: 
      rabbitmq: rabbitmq
  template:
    metadata:
      labels:
        rabbitmq: rabbitmq
        system: event-bus
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: event-bus-password
        volumeMounts:
        - name: event-bus-data
          mountPath: /var/lib/rabbitmq/mnesia
      volumes:
      - name: event-bus-data
        persistentVolumeClaim:
          claimName: event-bus-data
    