apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  seed-initial-data: "True"
  event-bus-host: event-bus
  event-bus-user: rabbitmquser
  notifications-allowed-origins: http://localhost
  web-identity-endpoint: http://identity-service:5005
  web-students-endpoint: http://students-service:5003
  web-payments-endpoint: http://payments-service:5011
  web-statistics-endpoint: http://statistics-service:5013
  web-outstandingpayments-endpoint: http://outstandingpayments-service:5009
  watchdog-web-health: http://web-client:5001/health
  watchdog-identity-health: http://identity-service:5005/health
  watchdog-students-health: http://students-service:5003/health
  watchdog-payments-health: http://payments-service:5011/health
  watchdog-statistics-health: http://statistics-service:5013/health
  watchdog-notifications-health: http://notifications-service:5004/health

---

apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  identity-database-sa-password: aWRlbnRpdHlEYXRhYmFzZVBhc3N3b3JkMTIhQA==
  students-database-sa-password: c3R1ZGVudHNEYXRhYmFzZVBhc3N3b3JkMTIhQA==
  payments-database-sa-password: cGF5bWVudHNEYXRhYmFzZVBhc3N3b3JkMTIhQA==
  statistics-database-sa-password: c3RhdGlzdGljc0RhdGFiYXNlUGFzc3dvcmQxMiFA
  web-database-sa-password: d2ViRGF0YWJhc2VQYXNzd29yZDEyIUA=
  security-token-secret: UGluayBGbHVmZnkgVW5pY29ybnMgRGFuY2luZyBvbiB0aGUgUmFpbmJvdw==
  identity-service-connection-string: U2VydmVyPWlkZW50aXR5LWRhdGFiYXNlO0RhdGFiYXNlPVpvcmFJZGVudGl0eURhdGFiYXNlO1VzZXIgSWQ9c2E7IFBhc3N3b3JkPWlkZW50aXR5RGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
  students-service-connection-string: U2VydmVyPXN0dWRlbnRzLWRhdGFiYXNlO0RhdGFiYXNlPVpvcmFTdHVkZW50c0RhdGFiYXNlO1VzZXIgSWQ9c2E7IFBhc3N3b3JkPXN0dWRlbnRzRGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
  payments-service-connection-string: U2VydmVyPXBheW1lbnRzLWRhdGFiYXNlO0RhdGFiYXNlPVpvcmFQYXltZW50c0RhdGFiYXNlO1VzZXIgSWQ9c2E7IFBhc3N3b3JkPXBheW1lbnRzRGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWUK
  statistics-service-connection-string: U2VydmVyPXN0YXRpc3RpY3MtZGF0YWJhc2U7RGF0YWJhc2U9Wm9yYVN0YXRpc3RpY3NEYXRhYmFzZTtVc2VyIElkPXNhOyBQYXNzd29yZD1zdGF0aXN0aWNzRGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWUKCg==
  web-service-connection-string: U2VydmVyPXdlYi1kYXRhYmFzZTtEYXRhYmFzZT1ab3JhRGF0YWJhc2U7VXNlciBJZD1zYTsgUGFzc3dvcmQ9d2ViRGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWUK
  event-bus-password: cmFiYml0bXFQYXNzd29yZDEyIQ==